"""
Agent 1 — Hallucination Checker

Catches conflicts between the deterministic IMNCI rule engine decision
and the LLM-generated explanation. A contradiction (e.g. RED triage but
explanation says "rest at home") could endanger a patient's life.

This agent sends both outputs to Groq, detects conflicts, and returns
a corrected explanation when needed.
"""

import os
import json
import time
from datetime import datetime, timezone
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

CONFLICT_CHECK_PROMPT = """You are a medical safety checker.
Rule engine decision: {rule_decision} (RED/YELLOW/GREEN)
LLM explanation text: {llm_explanation}

Does the explanation CONTRADICT the decision?
For example: decision is RED but explanation says 'rest at home' = contradiction.
Decision is YELLOW but explanation says 'no need to see a doctor' = contradiction.
Decision is GREEN but explanation says 'rush to hospital immediately' = contradiction.

Reply with JSON only, no other text:
{{
  "conflict": true or false,
  "reason": "one sentence why",
  "safe_explanation": "corrected explanation that matches the decision (or original if no conflict)"
}}"""


def check_hallucination(rule_decision: str, llm_explanation: str, groq_client=None) -> dict:
    """
    Check if the LLM explanation contradicts the rule engine decision.

    Args:
        rule_decision: "RED", "YELLOW", or "GREEN" from IMNCI triage engine.
        llm_explanation: The explanation text generated by Groq LLM.
        groq_client: Optional pre-initialised Groq client. If None, creates one.

    Returns:
        {
            'conflict_detected': True/False,
            'original_explanation': original text,
            'final_explanation': safe corrected text (or original if no conflict),
            'reason': why it was flagged (or 'No conflict detected'),
            'time_taken': seconds taken for the check
        }
    """
    start_time = time.time()

    result = {
        "conflict_detected": False,
        "original_explanation": llm_explanation,
        "final_explanation": llm_explanation,
        "reason": "No conflict detected",
        "time_taken": 0,
    }

    if not GROQ_API_KEY:
        result["reason"] = "Groq API key not set — skipped hallucination check"
        result["time_taken"] = round(time.time() - start_time, 3)
        return result

    try:
        client = groq_client or Groq(api_key=GROQ_API_KEY)

        prompt = CONFLICT_CHECK_PROMPT.format(
            rule_decision=rule_decision,
            llm_explanation=llm_explanation,
        )

        chat_completion = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.1,
            max_tokens=300,
        )

        response_text = chat_completion.choices[0].message.content.strip()

        # Parse JSON — handle potential markdown code fences
        cleaned = response_text
        if "```" in cleaned:
            cleaned = cleaned.split("```")[1]
            if cleaned.startswith("json"):
                cleaned = cleaned[4:]
        cleaned = cleaned.strip()

        parsed = json.loads(cleaned)

        if parsed.get("conflict", False):
            result["conflict_detected"] = True
            result["reason"] = parsed.get("reason", "Conflict detected by safety checker")
            result["final_explanation"] = parsed.get("safe_explanation", llm_explanation)

            # Log the conflict
            _log_conflict(rule_decision, llm_explanation, result["final_explanation"], result["reason"])
        else:
            result["reason"] = parsed.get("reason", "No conflict detected")

    except json.JSONDecodeError as e:
        result["reason"] = f"Failed to parse safety check response: {e}"
    except Exception as e:
        result["reason"] = f"Hallucination check failed: {e}"

    result["time_taken"] = round(time.time() - start_time, 3)
    return result


def _log_conflict(rule_decision: str, original: str, corrected: str, reason: str):
    """Log detected conflict to agent_logs.json."""
    log_entry = {
        "agent": "hallucination_checker",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "rule_decision": rule_decision,
        "original_explanation": original,
        "corrected_explanation": corrected,
        "reason": reason,
    }

    log_path = os.path.join(os.path.dirname(__file__), "agent_logs.json")
    try:
        if os.path.exists(log_path):
            with open(log_path, "r") as f:
                logs = json.load(f)
        else:
            logs = []
        logs.append(log_entry)
        with open(log_path, "w") as f:
            json.dump(logs, f, indent=2)
    except Exception:
        pass  # Never crash the app over logging


# ── Quick self-test ─────────────────────────────────────
if __name__ == "__main__":
    print("Testing hallucination checker...")
    # Test with a clear conflict
    test = check_hallucination(
        "RED",
        "The child seems fine. Let them rest at home and drink plenty of fluids.",
    )
    print(f"Conflict detected: {test['conflict_detected']}")
    print(f"Reason: {test['reason']}")
    print(f"Final explanation: {test['final_explanation']}")
    print(f"Time taken: {test['time_taken']}s")
